//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace commUtils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommunicationUtils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;rcs:Message 
        ///	xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns:rcs=&quot;http://www.transport.bombardier.com/2014/RcsCmm&quot;
        ///	xmlns:rcswds=&quot;http://www.transport.bombardier.com/2014/RcsCmm/wds&quot;
        ///	xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;	
        ///
        ///	&lt;hdr&gt;
        ///		&lt;source&gt;{0}&lt;/source&gt;
        ///		&lt;messageId&gt;rcs.e2k.ctc.{0}-{1}&lt;/messageId&gt;
        ///		&lt;content&gt;rcswds:processStarted&lt;/content&gt;
        ///	&lt;/hdr&gt;
        ///	&lt;data&gt;
        ///		&lt;rcswds:processStarted sourceId=&quot;{0}&quot;/&gt;
        ///	&lt;/data&gt;
        ///&lt;/rcs:Message&gt;
        ///.
        /// </summary>
        internal static string WDMessageStarted {
            get {
                return ResourceManager.GetString("WDMessageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;rcs:Message 
        ///	xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///	xmlns:rcs=&quot;http://www.transport.bombardier.com/2014/RcsCmm&quot;
        ///	xmlns:rcswds=&quot;http://www.transport.bombardier.com/2014/RcsCmm/wds&quot;
        ///	xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///
        ///	&lt;hdr&gt;
        ///		&lt;source&gt;{0}&lt;/source&gt;
        ///		&lt;messageId&gt;rcs.e2k.ctc.{0}-{1}&lt;/messageId&gt;
        ///		&lt;correlationId&gt;{2}&lt;/correlationId&gt;
        ///		&lt;content&gt;rcswds:processStateReport&lt;/content&gt;
        ///	&lt;/hdr&gt;
        ///	&lt;data&gt;
        ///		&lt;rcswds:processStateReport sourceId=&quot;{0}&quot;&gt;
        ///			&lt;tsn&gt;{3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WDProcessStateReport {
            get {
                return ResourceManager.GetString("WDProcessStateReport", resourceCulture);
            }
        }
    }
}
