//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace XSD {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bombardier.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bombardier.com", IsNullable=false)]
    public partial class configuration {
        
        private connection connectionField;
        
        private watchdog watchdogField;
        
        private Logging loggingField;
        
        /// <remarks/>
        public connection connection {
            get {
                return this.connectionField;
            }
            set {
                this.connectionField = value;
            }
        }
        
        /// <remarks/>
        public watchdog watchdog {
            get {
                return this.watchdogField;
            }
            set {
                this.watchdogField = value;
            }
        }
        
        /// <remarks/>
        public Logging Logging {
            get {
                return this.loggingField;
            }
            set {
                this.loggingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bombardier.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bombardier.com", IsNullable=false)]
    public partial class connection {
        
        private queues queuesField;
        
        private topics topicsField;
        
        private schemas schemasField;
        
        private string hostField;
        
        private int portField;
        
        private string logLevelField;
        
        private string userField;
        
        private string passwordField;
        
        public connection() {
            this.logLevelField = "Fatal";
            this.userField = "guest";
            this.passwordField = "guest";
        }
        
        /// <remarks/>
        public queues queues {
            get {
                return this.queuesField;
            }
            set {
                this.queuesField = value;
            }
        }
        
        /// <remarks/>
        public topics topics {
            get {
                return this.topicsField;
            }
            set {
                this.topicsField = value;
            }
        }
        
        /// <remarks/>
        public schemas schemas {
            get {
                return this.schemasField;
            }
            set {
                this.schemasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string host {
            get {
                return this.hostField;
            }
            set {
                this.hostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int port {
            get {
                return this.portField;
            }
            set {
                this.portField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("Fatal")]
        public string logLevel {
            get {
                return this.logLevelField;
            }
            set {
                this.logLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("guest")]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("guest")]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bombardier.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bombardier.com", IsNullable=false)]
    public partial class queues {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bombardier.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bombardier.com", IsNullable=false)]
    public partial class topics {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bombardier.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bombardier.com", IsNullable=false)]
    public partial class schemas {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bombardier.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bombardier.com", IsNullable=false)]
    public partial class watchdog {
        
        private string sendToField;
        
        private string receiveFromField;
        
        private string appNameField;
        
        private string modeField;
        
        public watchdog() {
            this.modeField = "automatic";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sendTo {
            get {
                return this.sendToField;
            }
            set {
                this.sendToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string receiveFrom {
            get {
                return this.receiveFromField;
            }
            set {
                this.receiveFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string appName {
            get {
                return this.appNameField;
            }
            set {
                this.appNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute("automatic")]
        public string mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bombardier.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bombardier.com", IsNullable=false)]
    public partial class Logging {
        
        private LogLevel logLevelField;
        
        /// <remarks/>
        public LogLevel LogLevel {
            get {
                return this.logLevelField;
            }
            set {
                this.logLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bombardier.com")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.bombardier.com", IsNullable=false)]
    public partial class LogLevel {
        
        private string defaultField;
        
        /// <remarks/>
        public string Default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    }
}
